import type { Achievement } from "@/types";

export const achievements: Achievement[] = [
  {
    id: "ach-1",
    title: "Learning Go",
    issuer: "LinkedIn Learning",
    date: "2024-01",
    type: "certification",
    description: "Completed structured Go programming course covering concurrency, interfaces, and cloud-native patterns.",
  },
  {
    id: "ach-2",
    title: "AWS for Developers: DynamoDB",
    issuer: "LinkedIn Learning",
    date: "2023-01",
    type: "certification",
    description: "In-depth course on DynamoDB data modelling, access patterns, and AWS SDK integration for developers.",
  },
  {
    id: "ach-3",
    title: "React.js Essential Training, Hooks & Accessibility",
    issuer: "LinkedIn Learning",
    date: "2023-06",
    type: "certification",
    description: "Comprehensive React training covering hooks, performance optimisation, and accessibility best practices.",
  },
  {
    id: "ach-4",
    title: "Scala 3",
    issuer: "LinkedIn Learning",
    date: "2023-09",
    type: "certification",
    description: "Functional programming with Scala 3 including new syntax, type system improvements, and pattern matching.",
  },
  {
    id: "ach-5",
    title: "Currently Pursuing: Advanced AI/ML",
    issuer: "Self-directed",
    date: "2025-01",
    type: "certification",
    description: "Advanced courses in LangChain, Agentic AI, and GenAI application development to build next-generation intelligent applications.",
  },
  {
    id: "ach-6",
    title: "AI-Enhanced Product Launch — Memoa",
    issuer: "Independent",
    date: "2024-01",
    type: "milestone",
    description: "Led Memoa product launch with AI-driven features, securing 100+ users and 10 paying customers within one week of release.",
  },
  {
    id: "ach-7",
    title: "Blockchain Innovation at ConsenSys",
    issuer: "ConsenSys",
    date: "2019-06",
    type: "milestone",
    description: "Designed an Ethereum-based document management system using Solidity smart contracts — a pioneering project in decentralised document verification.",
  },
  {
    id: "ach-8",
    title: "Payment Systems Integration — CineaCloud",
    issuer: "CineaCloud",
    date: "2020-06",
    type: "milestone",
    description: "Integrated Stripe for CineaCloud with multi-currency support, improving payment processing efficiency by 35%.",
  },
  {
    id: "ach-9",
    title: "Team Leadership — 20 Engineers",
    issuer: "QBurst",
    date: "2019-01",
    type: "award",
    description: "Mentored a team of 20 engineers, increasing productivity by 30% and improving delivery timelines across multiple enterprise projects.",
  },
  {
    id: "ach-10",
    title: "Technology Speaker — Java User Group (JUG)",
    issuer: "Java User Group",
    date: "2023-01",
    type: "award",
    description: "Presented at Java User Group (JUG) meetups on emerging technologies, sharing expertise with the wider developer community.",
  },
  {
    id: "ach-11",
    title: "E-commerce Innovation — Shopify Platform",
    issuer: "Shaklee Corporation",
    date: "2020-01",
    type: "milestone",
    description: "Pioneered Shopify app development using Node.js and React, enabling personalised product recommendation features for a health and wellness brand.",
  },
  {
    id: "ach-12",
    title: "Cloud Architecture — Multi-Platform Solutions",
    issuer: "QBurst",
    date: "2018-01",
    type: "milestone",
    description: "Designed cost-effective cloud solutions across AWS, DigitalOcean, and Linode platforms for diverse enterprise clients.",
  },
];
