import type { ResumeData } from "@/types";

export const resumeData: ResumeData = {
  summary:
    "Senior Software Engineer with 10+ years of experience building scalable enterprise applications and cloud-native systems. Specialized in full-stack development using Java/Spring Boot and Node.js/NestJS backends with React/Next.js frontends, architecting solutions on AWS. Expert in Infrastructure as Code, DevOps automation, and microservices architecture. Currently expanding into AI-driven development — Generative AI, Agentic AI, OpenAI, LangChain — to build intelligent, cloud-optimized applications.",

  workExperience: [
    {
      id: "we-1",
      company: "CHEP",
      title: "Senior Software Engineer",
      location: "London, UK",
      startDate: "2025-03",
      endDate: null,
      description:
        "Developing Java 17 microservices and leading access control and identity management initiatives for enterprise-scale applications.",
      achievements: [
        "Developing Java 17 microservices with Spring Boot and Spring Security for enterprise applications",
        "Integrated Liquibase across all environments within 2 months, including team training and onboarding",
        "Automated user profile management using Okta workflows, reducing manual effort by 40% within 2 sprints",
        "Leading OktaFGA-based access control implementation and microservices migration",
        "Supporting React migration from Backbone and set up JSDefender obfuscation",
      ],
      techStack: [
        "Java 17",
        "Spring Boot",
        "Microservices",
        "AWS Lambda",
        "SQS",
        "ECS",
        "S3",
        "RDS",
        "DynamoDB",
        "Okta",
        "TypeScript",
        "React",
        "PostgreSQL",
        "Terraform",
        "Golang",
      ],
    },
    {
      id: "we-2",
      company: "Boston Consulting Group (BCG)",
      title: "Full Stack Engineer",
      location: "London, UK",
      startDate: "2023-10",
      endDate: "2025-03",
      description:
        "Built data integration platforms and AI-enhanced document processing workflows for one of the world's leading management consultancies.",
      achievements: [
        "Built transcript library system with APIs for data integration, onboarding 5 vendors within 3 months",
        "Developed AWS Lambda functions using Node.js for serverless data processing",
        "Migrated all deployments to Terraform, completing IaC transition in under 3 months",
        "Integrated GPT-4 and GenAI into document processing workflows",
      ],
      techStack: [
        "Node.js",
        "TypeScript",
        "React",
        "AWS Lambda",
        "SQS",
        "S3",
        "RDS",
        "PostgreSQL",
        "Terraform",
        "Java",
        "Spring Boot",
        "GPT-4",
        "GenAI",
        "Golang",
      ],
    },
    {
      id: "we-3",
      company: "Canto",
      title: "Senior Software Engineer",
      location: "Birmingham, UK",
      startDate: "2022-08",
      endDate: "2023-09",
      description:
        "Designed advanced search and analytics features for a digital asset management platform handling 10,000+ assets.",
      achievements: [
        "Designed advanced search functionality for digital asset management across 10,000+ assets",
        "Integrated MerlinOne's NOMAD API to enhance video search capabilities",
        "Developed storage analytics reports, optimising costs by 25%",
      ],
      techStack: [
        "Spring Boot",
        "AWS Lambda",
        "Redis",
        "React",
        "DynamoDB",
        "S3",
        "CloudFront",
        "RDS",
        "OpenSearch",
        "Jenkins",
      ],
    },
    {
      id: "we-4",
      company: "MarketAxess",
      title: "Software Developer",
      location: "London, UK",
      startDate: "2021-08",
      endDate: "2022-08",
      description:
        "Built backend services and OpenAPI-compliant REST APIs for a leading electronic trading platform.",
      achievements: [
        "Designed backend services using Spring Boot with React frontend integration",
        "Developed OpenAPI-compliant REST APIs and AWS Lambda functions for data processing",
        "Achieved 95%+ SonarQube quality gate compliance through comprehensive testing",
      ],
      techStack: [
        "Java",
        "Spring Boot",
        "Node.js",
        "Redis",
        "React",
        "AWS EC2",
        "S3",
        "Jenkins",
        "Docker",
        "SonarQube",
      ],
    },
    {
      id: "we-5",
      company: "Shaklee Corporation",
      title: "Full Stack Engineer",
      location: "Chicago, US",
      startDate: "2020-06",
      endDate: "2021-07",
      description:
        "Developed backend systems and AI-powered recommendation features for a health and wellness e-commerce platform.",
      achievements: [
        "Developed backend systems using Spring Boot for e-commerce platform",
        "Built expert recommendation systems for personalised product suggestions",
      ],
      techStack: ["Node.js", "React", "TypeScript", "Java", "Spring Boot", "MySQL", "AWS"],
    },
    {
      id: "we-6",
      company: "QBurst",
      title: "Senior Architect",
      location: "London, UK",
      startDate: "2017-11",
      endDate: "2020-06",
      description:
        "Led a team of 8 engineers architecting and delivering enterprise applications and microservices solutions for diverse clients.",
      achievements: [
        "Led team of 8 engineers in designing and delivering enterprise applications",
        "Architected microservices solutions ensuring scalability and maintainability",
        "Oversaw CI/CD processes and DevOps practices across multiple projects",
      ],
      techStack: [
        "Java",
        "Spring Boot",
        "MySQL",
        "MongoDB",
        "Redis",
        "React",
        "AWS CloudFront",
        "DynamoDB",
        "EC2",
        "S3",
        "RDS",
        "Microservices",
      ],
    },
    {
      id: "we-7",
      company: "Trafigura",
      title: "Senior Software Engineer",
      location: "London, UK",
      startDate: "2015-01",
      endDate: "2017-11",
      description:
        "Developed backend systems for front office trading applications at one of the world's largest commodity traders.",
      achievements: [
        "Developed backend for front office trading systems with TDD practices",
        "Implemented comprehensive testing using Mockito and TestNG",
      ],
      techStack: ["Java", "Spring Boot", "Spring Security", "RabbitMQ", "MySQL", "Scala"],
    },
  ],

  education: [
    {
      id: "edu-1",
      institution: "University (details to be added)",
      degree: "Bachelor's",
      field: "Computer Science / Engineering",
      startYear: 2007,
      endYear: 2011,
      location: "India",
    },
  ],

  skillCategories: [
    {
      category: "Backend",
      skills: [
        { name: "Java", level: "expert" },
        { name: "Spring Boot", level: "expert" },
        { name: "Spring Cloud", level: "advanced" },
        { name: "Node.js", level: "expert" },
        { name: "NestJS", level: "advanced" },
        { name: "Express.js", level: "advanced" },
        { name: "Microservices", level: "expert" },
        { name: "REST API", level: "expert" },
        { name: "GraphQL", level: "intermediate" },
      ],
    },
    {
      category: "Frontend",
      skills: [
        { name: "TypeScript", level: "expert" },
        { name: "React", level: "expert" },
        { name: "Next.js", level: "advanced" },
        { name: "Redux", level: "advanced" },
        { name: "React Query", level: "intermediate" },
        { name: "Tailwind CSS", level: "advanced" },
        { name: "JavaScript", level: "expert" },
      ],
    },
    {
      category: "Cloud & DevOps",
      skills: [
        { name: "AWS", level: "expert" },
        { name: "Terraform", level: "advanced" },
        { name: "Docker", level: "advanced" },
        { name: "Kubernetes", level: "intermediate" },
        { name: "GitHub Actions", level: "advanced" },
        { name: "GitLab CI", level: "advanced" },
        { name: "Jenkins", level: "intermediate" },
      ],
    },
    {
      category: "AI & Machine Learning",
      skills: [
        { name: "Generative AI", level: "intermediate" },
        { name: "LangChain", level: "intermediate" },
        { name: "OpenAI / GPT-4", level: "intermediate" },
        { name: "Agentic AI", level: "beginner" },
        { name: "Flowise", level: "beginner" },
        { name: "Spring AI", level: "intermediate" },
      ],
    },
    {
      category: "Databases",
      skills: [
        { name: "PostgreSQL", level: "advanced" },
        { name: "MySQL", level: "advanced" },
        { name: "DynamoDB", level: "advanced" },
        { name: "MongoDB", level: "intermediate" },
        { name: "Redis", level: "advanced" },
        { name: "ElasticSearch", level: "intermediate" },
      ],
    },
    {
      category: "Additional",
      skills: [
        { name: "System Design", level: "advanced" },
        { name: "Kafka", level: "intermediate" },
        { name: "TDD / Testing", level: "advanced" },
        { name: "Agile / Scrum", level: "expert" },
        { name: "Golang", level: "intermediate" },
        { name: "Scala", level: "intermediate" },
      ],
    },
  ],

  pdfUrl: "/resume.pdf",
};
